In [1]:
import numpy as np
import scipy.stats as stats
from statsmodels.stats.weightstats import _tconfint_generic as t_stat
from statsmodels.stats.weightstats import _zconfint_generic as z_stat

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):
zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110],
ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832].
Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [6]:
x_mean = zp.mean()
print(x_mean)

101.4


In [22]:
y_mean = ks.mean()
print(y_mean)

709.9


In [8]:
xy_mean = (zp * ks).mean()
print(xy_mean)

81141.7


In [14]:
xy_m = zp * ks
xy_m

array([ 14035,  25830, 166060, 183800,  18360,  51730,  35262, 135300,
        89520,  91520])

In [15]:
print(xy_m.sum())

811417


In [19]:
# Найдем ковариацию по формуле: cov(xy)=M(X*Y)-M(X)*M(Y)
cov_ks = xy_mean - x_mean * y_mean
print(cov_ks)

9157.839999999997


In [20]:
# Найдем ковариацию двух величин c помощью numpy:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [25]:
# Найдем ковариацию c помощью стандартной функции:
cov_ks2 = ((zp - zp.mean()) * (ks - ks.mean())).mean()
cov_ks2

9157.84

In [26]:
# Найдем коэффициент корреляции Пирсона c помощью ковариации и 
# среднеквадратичных отклонений двух признаков:
x_std = zp.std()
y_std = ks.std()
corr_ks = cov_ks / (x_std * y_std)
corr_ks

0.8874900920739158

In [16]:
# Найдем коэффициент корреляции Пирсона c помощью numpy:
np.corrcoef(zp, ks)[0, 1]

0.8874900920739162

In [17]:
np.corrcoef(zp, ks)

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])