In [28]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

###  Задание № 1. Найти с помощью NumPy SVD для матрицы.

In [29]:
A = np.array([[1,2,0],[0,0,5],[3,-4,2],[1,6,5],[0,1,0]])
print(f'Матрица А:\n{A}')

Матрица А:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [30]:
U, s, W = np.linalg.svd(A)
# Транспонируем матрицу W
V = W.T
D = np.zeros_like(A, dtype = float)
D[np.diag_indices(min(A.shape))] = s

In [31]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [32]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [33]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1.  0. -0. -0. -0.]
 [ 0.  1.  0. -0.  0.]
 [-0.  0.  1. -0. -0.]
 [-0. -0. -0.  1. -0.]
 [-0.  0. -0. -0.  1.]]


In [34]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [35]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


In [36]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1.  0.]]


### Задание № 2. Для матрицы из предыдущего задания найти: евклидову норму.
    

In [37]:
from numpy.linalg import norm

In [38]:
print(f' Евклидова норма матрицы A:\n{norm(A, ord=2)}')

 Евклидова норма матрицы A:
8.824868854820444


### Задание № 3. Для матрицы из предыдущего задания найти норму Фробениуса.

In [39]:
from numpy import linalg as LA

In [40]:
print(f' норма Фробениуса матрицы A:\n{LA.norm(A, ord=None)}')

 норма Фробениуса матрицы A:
11.045361017187261


In [46]:
print(norm(A,'fro'))

11.045361017187261


In [49]:
from numpy import sqrt

In [54]:
#Посчитаем норму Фробениуса по формуле: sqrt(sum(diag(x'*x))), где х - элементы диагонали матрицы D.
x = 8.82 ** 2 + 6.14 ** 2 + 2.53 ** 2
print(x)

121.89289999999998


In [55]:
x1 = sqrt(x)
print(x1)

11.04051176350082
