In [5]:
import numpy as np
import matplotlib.pyplot as plt
from numpy import linalg as ln
from numpy import *

In [2]:
# задача № 1.Решите линейную систему.
A = np.array([[1, 2, 3], [4, 0, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
det_a = ln.det(A)
print('det A =', det_a)
X = np.linalg.solve(A,B)
for t, x in zip(X, ["x1=", "x2=", "x3="]):
    print(x, t)

det A = 59.999999999999986
x1= -9.200000000000001
x2= 0.9000000000000004
x3= 6.466666666666666


In [3]:
A1 = np.linalg.inv(A)
print (A1)
np.dot(A1, B)

[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]


array([-9.2       ,  0.9       ,  6.46666667])

In [11]:
# задача № 2 Найдите псевдорешение:
A = np.array([[1, 2, -1], [3, 4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]])
B = np.array([1, 7, 12, 7, 15])
np.linalg.lstsq(A, B)

C:\Users\Pochkarenok\AppData\Local\Temp\ipykernel_1132\2055936940.py:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.41675177, -0.07591672, -0.2282347 ]),
 array([22.79876553]),
 3,
 array([15.46246938,  8.85765904,  4.63183733]))

In [12]:
np.dot(A, [1.41675177, -0.07591672, -0.2282347 ]) 
 

array([ 1.49315303,  3.94658843, 11.25712836,  3.97467704, 16.87824549])

In [13]:
np.dot(A, [1.41675177, -0.07591672, -0.2282347 ]) - B

array([ 0.49315303, -3.05341157, -0.74287164, -3.02532296,  1.87824549])

In [15]:
def Q(x, y, z):
    return((np.linalg.norm(np.dot(A, [x, y, z]) - B))** 2)
Q(1.41675177, -0.07591672, -0.2282347)

22.79876553333283

In [16]:
#  задача № 3 Сколько решений имеет линейная система. Если ноль – то измените вектор правой части так, чтобы система стала
# совместной, и решите ее.


In [14]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
det_a = ln.det(A)
print('det A =', det_a)

det A = -9.51619735392994e-16


In [31]:
np.linalg.matrix_rank(A)

2

In [127]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([12, 2, 1])
B1 = B.reshape(1, B.shape[0])
print(B)
print(B1)
AB = np.vstack((A, B1))      
print(AB)               
np.linalg.matrix_rank(AB)               

[12  2  1]
[[12  2  1]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [12  2  1]]


3

In [126]:
AB1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9],[0, 0, 0]])
np.linalg.matrix_rank(AB1)


2

In [64]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([0, 0, 0])
np.linalg.lstsq(A, B)

C:\Users\Pochkarenok\AppData\Local\Temp\ipykernel_1132\976763621.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([0., 0., 0.]),
 array([], dtype=float64),
 2,
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]))

In [62]:
# задача № 4.Вычислите LU-разложение матрицы.

In [97]:
import numpy as np
import scipy
import scipy.linalg

In [103]:
A = np.array([[1, 2, 3], [2, 16, 21], [4, 28, 73]])
P, L, U = scipy.linalg.lu(A)

print('P=')
print(P)
print('L=')
print(L)
print('U=')
print(U)
print(np.dot(P, A) - np.dot(L, U))

P=
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L=
[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]
U=
[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]
[[ -2. -12. -52.]
 [  3.  26.  70.]
 [ -1. -14. -18.]]


In [113]:
#  задача №5. Найдите нормальное псевдорешение недоопределенной системы:
# x+2y-z=1  8x-5y+2z=12 


In [125]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])
np.linalg.lstsq(A, B)

C:\Users\Pochkarenok\AppData\Local\Temp\ipykernel_1132\1817694967.py:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  np.linalg.lstsq(A, B)


(array([ 1.38191882, -0.18081181,  0.0202952 ]),
 array([], dtype=float64),
 2,
 array([9.65316119, 2.41173777]))

In [141]:
A = np.array([[1, 2, -1], [8, -5, 2]])
B = np.array([1, 12])
np.linalg.norm(X)


1.4999999999999893

In [142]:
np.linalg.norm(np.dot(A, X) - B)

0.5000000000000082

In [139]:
def Q(x, y, z):
    return(x ** 2 + y ** 2 + z ** 2)
Q(1.38191882, -0.18081181,  0.0202952)



1.942804430848709

In [144]:
def Q(x, y, z):
    return((np.linalg.norm(np.dot(A, [x, y, z]) - B))** 2)
Q(1.38191882, -0.18081181,  0.0202952)

1.0000001654807488e-16

In [112]:
print('Ответ: нормальное псевдорешение: x = 1.38191882, y = -0.18081181,  z = 0.0202952')

Ответ: нормальное псевдорешение: x = 1.38191882, y = -0.18081181,  z = 0.0202952


In [ ]:
# Задача № 6 Найдите одно из псевдорешений вырожденной системы:

In [116]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([2, 5, 11])
Q, R = linalg.qr(A)

print('A=')
print(A)
print('Q=')
print(Q)
print('R=')
print(R)

A=
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Q=
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]
R=
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.11164740e-15]]


In [118]:
print(np.dot(Q, R))
print(np.dot(np.transpose(Q), Q))      

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
[[ 1.00000000e+00 -5.26517217e-16 -2.55176183e-16]
 [-5.26517217e-16  1.00000000e+00  3.37757775e-16]
 [-2.55176183e-16  3.37757775e-16  1.00000000e+00]]


In [119]:
R1 = R[:2, :2]
R1

array([[-8.1240384 , -9.6011363 ],
       [ 0.        ,  0.90453403]])

In [120]:
B1 = np.dot(np.transpose(Q), B)[:2]
B1

array([-1.21860576e+01,  8.54871729e-15])

In [121]:
X1 = np.linalg.solve(R1, B1)
X1

array([1.50000000e+00, 9.45096256e-15])

In [122]:
X = np.append(X1, 0)
print(X)
np.linalg.norm(X)

[1.50000000e+00 9.45096256e-15 0.00000000e+00]


1.4999999999999893

In [124]:
print('Ответ: псевдорешение: x = 1.50000000e+00, x2 = 9.45096256e-15, x3 = 0.0000000')

Ответ: псевдорешение: x = 1.50000000e+00, x2 = 9.45096256e-15, x3 = 0.0000000
